# Deployment for the containers/pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devoirs-deployment
  labels:
    app: devoirs-depl
spec:
  replicas: 2
  selector:
    # Has to match the container label
    matchLabels:
      app: devoirs-pod
  template:
    metadata:
      labels:
        app: devoirs-pod
    spec:
      containers:
        - name: devoirs-pod
          image: aminerachyd/projetlms-devoirs
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
---
# Service for the containers/pods
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devoirs-service
  name: devoirs-service
spec:
  # Has to match the container label
  selector:
    app: devoirs-pod
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
