# Deployment for the containers/pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comptes-deployment
  labels:
    app: comptes-depl
spec:
  replicas: 1
  # replicas: 2
  selector:
    # Has to match the container label
    matchLabels:
      app: comptes-pod
  template:
    metadata:
      labels:
        app: comptes-pod
    spec:
      containers:
        - name: comptes-pod
          image: aminerachyd/projetlms-gestioncomptes
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
---
# Service for the containers/pods
apiVersion: v1
kind: Service
metadata:
  labels:
    app: comptes-service
  name: comptes-service
spec:
  # Has to match the container label
  selector:
    app: comptes-pod
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
