openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  '/storage/user/{userId}/files':
    get:
      tags:
        - stockage-controller
      operationId: listerFichiersSac
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: pagination
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageAssociationFichier'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - stockage-controller
      operationId: uploadFichierSac_1
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fichier:
                  type: string
                  format: binary
          application/json:
            schema:
              $ref: '#/components/schemas/ParamAssocId_Public'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AssociationFichier_Public'
                  - $ref: '#/components/schemas/AssociationFichier'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
  '/storage/class/{coursId}/files':
    post:
      tags:
        - stockage-controller
      operationId: ajoutFichierCours
      parameters:
        - name: coursId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParamAssocId_Public'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssociationFichier_Public'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
  '/storage/user/{userId}/files/{assocId}':
    get:
      tags:
        - stockage-controller
      operationId: getFichierSac
      parameters:
        - name: assocId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: byte
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
        - stockage-controller
      operationId: retraitFichierSac
      parameters:
        - name: assocId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
  '/storage/user/{userId}/files/{assocId}/info':
    get:
      tags:
        - stockage-controller
      operationId: getInfoFichierSac
      parameters:
        - name: assocId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssociationFichier_Public'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
  '/storage/cours/{coursId}/files':
    get:
      tags:
        - stockage-controller
      operationId: listerFichiersCours
      parameters:
        - name: coursId
          in: path
          required: true
          schema:
            type: string
        - name: pagination
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageAssociationFichier'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
  '/storage/class/{coursId}/files/{assocId}':
    get:
      tags:
        - stockage-controller
      operationId: getFichierCours
      parameters:
        - name: assocId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: coursId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: byte
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
        - stockage-controller
      operationId: retraitFichierCours
      parameters:
        - name: assocId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: coursId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
  '/storage/class/{coursId}/files/{assocId}/info':
    get:
      tags:
        - stockage-controller
      operationId: getInfoFichierCours
      parameters:
        - name: assocId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: coursId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssociationFichier_Public'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    AssociationFichier:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fichierInfo:
          $ref: '#/components/schemas/FichierInfo'
        typeAssociation:
          type: string
          enum:
            - COURS
            - PUBLICATION
            - DEVOIR
            - SAC
        idCorrespondantAssociation:
          type: string
    FichierInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        idProprietaire:
          type: integer
          format: int64
        dateCreation:
          type: string
          format: date-time
        nom:
          type: string
        chemin:
          type: string
        size:
          type: integer
          format: int64
        contentType:
          type: string
        associations:
          type: array
          items:
            $ref: '#/components/schemas/AssociationFichier'
    ParamAssocId_Public:
      type: object
      properties:
        assocId:
          type: integer
          format: int64
    AssociationFichier_Public:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fichierInfo:
          $ref: '#/components/schemas/FichierInfo_Public'
        typeAssociation:
          type: string
          enum:
            - COURS
            - PUBLICATION
            - DEVOIR
            - SAC
        idCorrespondantAssociation:
          type: string
    FichierInfo_Public:
      type: object
      properties:
        id:
          type: integer
          format: int64
        idProprietaire:
          type: integer
          format: int64
        chemin:
          type: string
        associations:
          type: array
          items:
            $ref: '#/components/schemas/AssociationFichier_Public'
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
    PageAssociationFichier:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        pageable:
          $ref: '#/components/schemas/Pageable'
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/AssociationFichier'
        empty:
          type: boolean
    Sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean
