name: Docker Image CI

on:
  push:
    branches: [ master ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to dockerhub
      env: 
        DOCKER_USER: ${{secrets.DOCKERHUB_USER_WADII}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS_WADII}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS 
    - name: Build the image
      working-directory: ./service-service_cours
      run: docker build .  --tag wmordy/courseService:$(date +%s)
    - name: Push the image to dockerhub 
      run: docker push ${{secrets.DOCKER_USER}}/course-microservice
