name: "Test du service : Devoirs"

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "adopt"

      - name: Test avec Maven
        working-directory: ./service-devoirs
        run: mvn test

  image_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_RACHYD }}
          password: ${{ secrets.DOCKERHUB_TOKEN_RACHYD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./service-devoirs
          file: ./service-devoirs/Dockerfile
          push: true
          tags: aminerachyd/projetlms-devoirs
