name: "Test du service : Gestion de comptes"

on:
  push:
    branches: [amine]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "adopt"

      - name: Test avec Maven
        working-directory: ./service-gestioncomptes
        run: mvn test
